title: Mattis Kaemmerer
description: > # this means to ignore newlines until "baseurl:"
  Site of Mattis Kaemmerer, yet another happy computer scientist. :-)
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mkaemmerer.com" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: dark

# Profile information
name: Mattis Manfred Kaemmerer
tagline: Studying Computer Science at TU Darmstadt
about-description: Hello there! Currently, I study for a master's degree in computer science at TU Darmstadt. My courses are focused on machine learning and artificial intelligence. Whenever possible, I also love to teach because it feels so good to see people improve and it really helps me to evaluate my own skills. If there is something you would like to know, feel free to contact me. :)
pic: picture.jpg  # Place a 200x200 picture inside /assets/img/ folder

# Contact links
email: mattis.kaemmerer@gmx.de
linkedin: mattis-manfred-kaemmerer-173a20173
github: m8is
stackoverflow: 7511394
twitter: '@m8is'

# Comments
discus-identifier: m8is.disqus.com

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

plugins:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
